# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            
tagline:          'Existence'
description:      'Ritesh'
url:              https://riteshx95.github.io
baseurl:          /

author:
  name:           'Ritesh'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/riteshx95/riteshx95.github.io/

plugins:
  - jekyll-paginate
  - jekyll-gist
