# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Ritesh Ghanta'
tagline:          ''
description:      'Ritesh'
url:              https://riteshx95.github.io
baseurl:          https://riteshx95.github.io/
#baseurl:          /

author:          riteshx95
  name:           Ritesh Ghanta
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/riteshx95/riteshx95.github.io/

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
